backend/code/website/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from .forms import RegistrationForm, LoginForm, ResetPasswordEmailForm, ResetPasswordForm, EditProfileForm
from .models import User, Cart
from . import db, mail
from werkzeug.security import generate_password_hash, check_password_hash 
from flask_login import login_user, current_user, logout_user, login_required
import secrets
from flask_mail import Message
import datetime
from cryptography.fernet import Fernet


auth = Blueprint('auth', __name__)

# Method to verify user login information
@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    # Check if form is valid
    if form.validate_on_submit():
        # Check if the user exists in the database
        user = User.query.filter_by(email=form.email.data).first()
        # Check if the password is correct
        if user and check_password_hash(user.password, form.password.data):
            # If if the user's email is verified
            if user.is_verified:
                if user.is_admin:
                    login_user(user)
                    flash('Login successful!', 'success')
                    return redirect(url_for('views.admin_page'))
                login_user(user)
                # Initialize the user's cart on login
                session["cart"] = {}
                flash('Login successful!', 'success')
                return redirect(url_for('views.home'))
            else:
                flash('Account Not Verified. Please Verify Account.', 'error')
        else:
            flash('Invalid email or password. Please try again.', 'error')
    else:
        # Outputting Errors
        for error, message in zip(form.errors.keys(), form.errors.values()):
            flash(f'{error.capitalize()} Error: {message[0]}')
    return render_template('Login.html', form = form)

# Method to verify a user's registration information and create a new user
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegistrationForm()
    # Check if form is valid
    if form.validate_on_submit():
        # Check if the email is already registered
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user:
            flash('Email already registered. Please log in instead.', 'error')
            return redirect(url_for('auth.login'))  # Redirect to login page if user already exists
        # Check if the password and confirm password fields match
        if form.password.data != form.confirm_password.data:
            flash('Passwords do not match. Please try again.', 'error')
            return redirect(url_for('auth.signup'))

        # If the email is not already registered, create a new User instance
        new_user = User(
            name=form.name.data,
            phone=form.phone.data,
            email=form.email.data,
            password= generate_password_hash(form.password.data, 'sha256')
        )

        # Record email for verification
        email = form.email.data
        new_user.generate_verification_token()

        token = new_user.verification_token

        # Save the new user to the database
        db.session.add(new_user)
        db.session.commit()

        # Send the verification email
        msg = Message('Account Verification', sender='your_gmail_username', recipients=[email])
        msg.body = f'Click the following link to verify your account: {url_for("auth.verify_account", token=token, _external=True)}'
        mail.send(msg)

        flash('Registration successful! You may proceed to the email verification page.', 'success')
        return redirect(url_for('auth.email_verification'))
    else:
        # Outputting Errors
        for error, message in zip(form.errors.keys(), form.errors.values()):
            flash(f'{error.capitalize()} Error: {message[0]}')

    return render_template('Registration.html', form = form)

# Method to update a user's verification status
@auth.route('/verify-account/<token>')
def verify_account(token):
    # Query for user data
    user = User.query.filter_by(verification_token=token).first()

    # Check if the user exists and if the token is valid
    if not user or user.verification_token_expiration < datetime.datetime.utcnow():
        flash('Invalid or expired verification token.', 'error')
        return redirect(url_for('auth.login'))

    # Update the database to verify the user's account
    user.is_verified = True
    user.verification_token = None
    user.verification_token_expiration = None
    db.session.commit()

    flash('Your account has been verified successfully. You can now log in.', 'success')
    return redirect(url_for('auth.login'))  # Redirect to the login page

# Method to redirect user view to confirm email confirmation
@auth.route('/email-verification')
def email_verification():
    return render_template('RegistrationEmailVerification.html')

# Method to log out a user
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    # Redirect the user to the desired page (e.g., home page or login page)
    return redirect(url_for('views.home'))

# Method to send a forgot password email
@auth.route('/forgot-password', methods=['GET', 'POST'])
def forgot_password_email():
    form = ResetPasswordEmailForm()
    # Check if the form is valid
    if form.validate_on_submit():
        # Process the form data
        email = form.email.data
        # Find the user's account in the database via email
        user = User.query.filter_by(email=email).first()
        
        # If the user exists, generate a reset token and send the reset password email
        if user:
            token = secrets.token_urlsafe(16)  # Generate a token with 16 bytes (128 bits)
            user.reset_token = token
            user.reset_token_expiration = datetime.datetime.utcnow() + datetime.timedelta(hours=1)  # Set expiration to one hour from now
            db.session.commit()

            # Create the reset password email message
            msg = Message('Password Reset Request', sender='your_gmail_username', recipients=[email])
            # Set the content of the email (you can use HTML templates for a better email layout)
            msg.body = f'Click the following link to reset your password: {url_for("auth.reset_password", token=token, _external=True)}'
            # Send the email
            mail.send(msg)
            return render_template('ResetPasswordCorrectEmail.html')
        else: 
            return render_template('ResetPasswordIncorrectEmail.html')

    return render_template('ResetPasswordEmail.html', form=form)

# Method to reset a user's password
@auth.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    # Check if the reset token is associated with a user account
    user = User.query.filter_by(reset_token=token).first()
    if not user:
        flash('Invalid token. Please request a new password reset.', 'error')
        return redirect(url_for('auth.forgot_password_email'))

    form = ResetPasswordForm()
    # Validate Password Reset Data
    if form.validate_on_submit():
       # Check if the password and confirm password fields match
        if form.password.data != form.confirm_password.data:
            flash('Passwords do not match. Please try again.', 'error')
            return redirect(url_for('auth.reset_password', token=token))
       
        # Update the user's password with the new password
        user.password = generate_password_hash(form.password.data, 'sha256')

        # Clear the reset token from the user's account after successful password reset
        user.reset_token = None
        user.reset_token_expiration = None

        # Save the changes to the database
        db.session.commit()

        # Confirm password reset to user
        flash('Your password has been reset successfully. You can now log in with your new password.', 'success')
        return redirect(url_for('auth.login'))
    else:
        # Outputting Errors
        for error, message in zip(form.errors.keys(), form.errors.values()):
            flash(f'{error.capitalize()} Error: {message[0]}')

    return render_template('ResetPassword.html', form=form, token = token)

# Method to edit a user's profile
@auth.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()

    # Load the current user's information into the form fields
    if request.method == 'GET':
        form.name.data = current_user.name
        form.phone.data = current_user.phone

        form.street.data = current_user.street
        form.city.data = current_user.city
        form.state.data = current_user.state
        #form.zipcode.data = current_user.zipcode

        #form.card_type.data = current_user.card_type
        #form.card_number.data = current_user.decrypt_card_number()
        form.expiration_date.data = current_user.expiration_date
        #form.security_code.data = current_user.decrypt_security_code()
    # Validate the form data
    if form.validate_on_submit():
        # Save the changes to the user's profile
        user = User.query.get(current_user.id)
        user.name = form.name.data
        user.phone = form.phone.data

        user.street = form.street.data
        user.city = form.city.data
        user.state = form.state.data
        user.zipcode = form.zipcode.data

        # Encrypt the card number and security code
        user.card_type = form.card_type.data
        if form.card_number.data:
            user.card_number_encrypted = user.encrypt(str(form.card_number.data))
        user.expiration_date = form.expiration_date.data

        if form.security_code.data:
            user.security_code_encrypted = user.encrypt(str(form.security_code.data))

        if form.password.data:
            user.password = generate_password_hash(form.password.data, 'sha256')
        

backend/code/website/views.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from flask_login import login_required, current_user
from .models import Book, Order, Cart, CartItem, Book
import random
from .forms import PaymentForm
views = Blueprint('views', __name__)

# Home page
@views.route('/')
@views.route('/home')
def home():
    random.seed(42)
    # Fetch all books from the database
    all_books = Book.query.all()
    # Select a random subset of books to display on the front page
    # Change the number (e.g., 4) to the desired number of random books you want to display
    if len(all_books) > 4:
        random_books = random.sample(all_books, 4)
    else:
        random_books = all_books

    # Get the 4 most recent books added to the database, reverse the list
    new_books = all_books[::-1][:4]

    # Pass the random_books to the front page (home.html) template
    return render_template('home.html', featured_books=random_books, new_books=new_books)

# Cart page
@views.route('/cart')
@login_required
def cart():
    # Get the session cart or create a new one if it doesn't exist
    cart = session.get('cart', {})
    books = []
    quantities = []
    for book_id, quantity in zip(cart.keys(), cart.values()):
        book = Book.query.get_or_404(book_id)
        books.append(book)
        quantities.append(quantity)

    return render_template('Cart.html', books=books, quantities=quantities, zip=zip)


# Checkout page
@views.route('/checkout', methods=['GET', 'POST'])
@login_required
def checkout():
    form = PaymentForm()
    cart = session.get('cart', {})
    books = []
    quantities = []
    total = 0.0
    for book_id, quantity in zip(cart.keys(), cart.values()):
        book = Book.query.get_or_404(book_id)
        books.append(book)
        quantities.append(quantity)
        total += book.selling_price * quantity
    session["total"] = total


    if form.validate_on_submit():
        session["promo_code"] = form.promo_code.data
        session["card_number"] = form.card_number.data
        session["expiration_date"] = form.expiration_date_m.data + "/" + form.expiration_date_Y.data
        session["security_code"] = form.security_code.data
        session["save_card"] = form.save_card.data
        return redirect(url_for('purchase.checkout_cart'))
    else:
        # Outputting Errors
        for error, message in zip(form.errors.keys(), form.errors.values()):
            flash(f'{error.capitalize()} Error: {message[0]}')
    return render_template('Checkout.html', books=books, quantities=quantities, zip=zip, total=total, form=form)

# Product page
@views.route('/product/<int:book_id>')
def product(book_id):
    book = Book.query.get_or_404(book_id)
    return render_template('Product.html', book=book)


# Order History page
@views.route('/order-history')
@login_required
def order_history():
    # Get current user id
    user_id = current_user.id
    # Get all orders for the current user
    orders = Order.query.filter_by(userid=user_id).all()
    print(len(orders))
    # Get all the old carts for the current user
    carts = Cart.query.filter_by(userid=user_id).all()
    print(len(carts))
    # Get all the cart items for the old carts
    cart_items = []
    book_carts = []
    for cart in carts:
        print(cart)
        items = CartItem.query.filter_by(cartid=cart.id).all()
        books = []
        for item in items:
            books.append(Book.query.get(item.bookid))
        print(items)
        print(books)
        cart_items.append(items)
        book_carts.append(books)

    return render_template('OrderHistory.html', orders=orders, cart_items=cart_items, book_carts=book_carts, zip=zip)

# Admin Panel
@views.route('/admin-page')
def admin_page():
    return render_template('AdminPage.html')

backend/code/website/templates/Cart.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cart</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #F5EACF;
      color: #4F583D;
      padding: 20px;
    }
    
    h1 {
      text-align: center;
      margin-bottom: 20px;
    }
    
    ul.horizontal-menu {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #8A584C;
    }

    ul.horizontal-menu li {
      display: inline-block;
      margin-right: 10px;
    }

    ul.horizontal-menu li a {
      display: block;
      color: #fff;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }

    ul.horizontal-menu li a:hover {
      background-color: #70463e;
    }
    
    .cart-item {
      border: 1px solid #ccc;
      padding: 10px;
      margin-bottom: 20px;
    }
    
    .cart-item-details {
      margin-bottom: 10px;
    }
    
    .remove-button {
      background-color: #8A584C;
      border: none;
      color: white;
      padding: 10px 20px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin-top: 10px;
      cursor: pointer;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 10px;
    }

    th, td {
      border: 1px solid #8A584C;
      padding: 8px;
      text-align: left;
    }
    
    .checkout-button {
      background-color: #8A584C;
      border: none;
      color: white;
      padding: 10px 20px;
      text-align: center;
      text-decoration: none;
      display: block;
      font-size: 16px;
      margin-top: 20px;
      cursor: pointer;
      width: 100%;
    }
    
    .quantity-input {
      width: 50px;
      text-align: center;
      margin-right: 10px;
    }
  </style>
</head>
<body>
  <ul class="horizontal-menu">
    <li><a href="{{ url_for('views.home') }}">Home</a></li>
    <li><a href="{{ url_for('views.cart') }}">Cart</a></li>
    {% if current_user.is_authenticated %}
        {% if current_user.is_admin %}
            <li><a href="{{ url_for('views.admin_page') }}">Admin Page</a></li>
            <li><a href="{{ url_for('auth.edit_profile') }}">Edit Profile</a></li>
            <li><a href="{{ url_for('views.order_history') }}">Order History</a></li>
        {% else %}
            <li><a href="{{ url_for('auth.edit_profile') }}">Edit Profile</a></li>
            <li><a href="{{ url_for('views.order_history') }}">Order History</a></li>
        {% endif %}
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
    {% else %}
        <li><a href="{{ url_for('auth.signup') }}">Register</a></li>
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
    {% endif %}
  </ul>

  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="flash-messages">
        <ul>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}
  {% endwith %}

  <h1>Cart</h1>

  <div class="cart-item">
      <form action="{{ url_for('purchase.update_cart') }}" method="POST">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          {% for book, quantity in zip(books, quantities) %}
          <div class="cart-item-details">
              <h3>{{ book.title }}</h3>
              <p>Author: {{ book.author }}</p>
              <p>Price: ${{ book.selling_price }}</p>
          </div>
  
          <label for="quantity_{{ book.id }}">Quantity:</label>
          <input class="quantity-input" type="number" name="quantity_{{ book.id }}" value="{{ quantity }}" min="1">
  
          <input type="hidden" name="book_id_{{ book.id }}" value="{{ book.id }}">
          <button class="update-cart" type="submit">Update Cart</button>
  
          <button formaction="{{ url_for('purchase.remove_from_cart', book_id=book.id) }}"
              class="remove-from-cart" type="submit">Remove from Cart</button>
          {% endfor %}
      </form>
  </div>
  
  <!-- Add more cart items if necessary -->
  
  <button class="checkout-button"><a href="{{ url_for('views.checkout') }}" style="color: white; text-decoration: none;">Proceed to Checkout</a></button>
</body>
</html>

backend/code/website/templates/Home.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Book Store Home Page</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    body {
      font-family: Arial, sans-serif;
      margin: 0 auto;
      max-width: 1200px;
      padding: 20px;
    }

    header {
      align-items: center;
      display: flex;
      margin-bottom: 25px;
    }

    nav {
      margin-left: 30px;
    }

    .product-cards {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      grid-gap: 20px;
      margin-bottom: 30px;
    }

    nav ul {
      display: flex;
      list-style: none;
    }

    nav a {
      color: black;
      font-weight: bold;
      display: block;
      padding: 15px;
      text-decoration: none;
      transition: color 0.3s ease;
    }

    nav a:hover {
      color: #70463e;
      text-decoration: underline;
    }

    .breadcrumb {
      display: flex;
      list-style: none;
    }

    .breadcrumb li {
      padding: 10px;
    }

    .breadcrumb li:after {
      content: "/";
      margin-left: 20px;
    }

    .breadcrumb li:last-child:after {
      content: "";
    }

    .breadcrumb a {
      color: black;
      text-decoration: none;
    }

    .breadcrumb a:hover {
      text-decoration: underline;
    }

    .intro {
      margin: 30px 0;
      padding-left: 10px;
      width: 50%;
    }

    .intro h1 {
      margin-bottom: 15px;
    }

    .intro p {
      line-height: 1.5;
    }

    .product-card {
      display: flex;
      flex-direction: column;
      align-items: center;
      border: 1px solid #ccc;
      padding: 15px;
      background-color: #fff;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      transition: box-shadow 0.3s ease;
    }

    .product-card:hover {
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .product-card a {
      color: black;
      text-decoration: none;
    }

    .product-card img {
      width: 100%;
      height: 200px;
      object-fit: cover;
      margin-bottom: 10px;
    }

    .product-card h2 {
      margin: 10px 0;
    }

    .product-card p {
      line-height: 1.5;
    }

    .current-price span {
      font-weight: bold;
      text-decoration: underline;
    }

    .saving {
      color: green;
    }

    ul.horizontal-menu {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #8A584C;
    }

    ul.horizontal-menu li {
      display: inline-block;
      margin-right: 10px;
    }

    ul.horizontal-menu li a {
      display: block;
      color: #fff;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      transition: background-color 0.3s ease;
    }

    ul.horizontal-menu li a:hover {
      background-color: #70463e;
    }

    .search-form {
      display: inline-block;
      vertical-align: middle;
    }

    .search-form input[type="text"] {
      width: 150px;
      padding: 8px;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    .search-form select {
      padding: 8px;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    .search-form button[type="submit"] {
      background-color: #4CAF50;
      border: none;
      color: white;
      padding: 8px 12px;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .search-form button[type="submit"]:hover {
      background-color: #45a049;
    }
    
        .add-to-cart {
      background-color: #3498db;
      border: none;
      color: white;
      padding: 8px 16px;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .add-to-cart:hover {
      background-color: #2980b9;
    }
  </style>
</head>

<body>
  <ul class="horizontal-menu">
    <li><a href="{{ url_for('views.home') }}">Home</a></li>
    <li><a href="{{ url_for('views.cart') }}">Cart</a></li>
    {% if current_user.is_authenticated %}
    {% if current_user.is_admin %}
    <li><a href="{{ url_for('views.admin_page') }}">Admin Page</a></li>
    <li><a href="{{ url_for('auth.edit_profile') }}">Edit Profile</a></li>
    <li><a href="{{ url_for('views.order_history') }}">Order History</a></li>
    {% else %}
    <li><a href="{{ url_for('auth.edit_profile') }}">Edit Profile</a></li>
    <li><a href="{{ url_for('views.order_history') }}">Order History</a></li>
    {% endif %}
    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
    {% else %}
    <li><a href="{{ url_for('auth.signup') }}">Register</a></li>
    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
    {% endif %}
    <li class="search-form">
      <form id="search-form" action="{{ url_for('search.lookup') }}" method="GET">
        <input type="text" id="search-input" name="query" placeholder="Search..." required>
        <select id="search-criteria" name="criteria">
          <option value="title">Search by Title</option>
          <option value="author">Search by Author</option>
          <option value="genre">Search by Genre</option>
          <option value="ISBN">Search by ISBN</option>
        </select>
        <button type="submit">Search</button>
      </form>
    </li>
  </ul>

  <h1>Home</h1>

  {% with messages = get_flashed_messages() %}
  {% if messages %}
  <div class="flash-messages">
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
  </div>
{% endif %}
  {% endwith %}

  <section class="product-cards">
    <h2>Featured Books<br></h2>
    {% for book in featured_books %}
    <div class="product-card">
        <img src="{{ book.image_url }}" alt="" />
        <h2><a href="{{ url_for('views.product', book_id=book.id) }}">{{ book.title }}</a></h2>
        <p class="current-price">Price you pay: <span>${{ book.selling_price }}</span></p>
        <form action="{{ url_for('purchase.add_to_cart', book_id=book.id) }}" method="POST">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button class="add-to-cart" type="submit">Add to Cart</button>
        </form>
    </div>
    {% endfor %}
</section>

  <section class="product-cards">
    <h2>New Additions<br></h2>
    {% for book in new_books %}
    <div class="product-card">
        <img src="{{ book.image_url }}" alt="" />
        <h2><a href="{{ url_for('views.product', book_id=book.id) }}">{{ book.title }}</a></h2>
        <p class="current-price">Price you pay: <span>${{ book.selling_price }}</span></p>
        <form action="{{ url_for('purchase.add_to_cart', book_id=book.id) }}" method="POST">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button class="add-to-cart" type="submit">Add to Cart</button>
        </form>
    </div>
    {% endfor %}
  </section>
</body>

</html>

backend/code/website/templates/SearchView.html
<!DOCTYPE html>
<html>
<head>
  <title>Online Bookstore</title>
  <style>

    body {
      font-family: Arial, sans-serif;
      background-color: #f1f1f1;
      padding: 20px;
    }
    h1 {
      text-align: center;
    }
    form {
      max-width: 300px;
      margin: 0 auto;
      background-color: #fff;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    input[type="text"],
    input[type="password"] {
      width: 100%;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      box-sizing: border-box;
      border-radius: 4px;
    }
    input[type="submit"] {
      width: 100%;
      background-color: #4CAF50;
      color: white;
      padding: 14px 20px;
      margin: 8px 0;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    input[type="submit"]:hover {
      background-color: #45a049;
    }
    ul.horizontal-menu {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #8A584C;
    }

    ul.horizontal-menu li {
      display: inline-block;
      margin-right: 10px;
    }

    ul.horizontal-menu li a {
      display: block;
      color: #fff;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      transition: background-color 0.3s ease;
    }

    ul.horizontal-menu li a:hover {
      background-color: #70463e;
    }

        /* CSS for displaying search results in a grid */
    .product-container {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      max-width: 1000px;
    }
    .product-card {
      width: 17%;
      margin-bottom: 20px;
      background-color: #fff;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      border-radius: 5px;
      padding: 20px;
    }
    .product-image {
      width: 100%;
      height: auto;
      max-height: 200px; /* Adjust the maximum height as needed */
      object-fit: cover;
      border-radius: 5px;
      margin-bottom: 10px;
    }
    .product-card h2 {
      margin-top: 10px;
      font-size: 18px;
    }
    .product-card p {
      margin: 8px 0;
    }
    .product-card button {
      background-color: #4CAF50;
      color: white;
      padding: 8px 12px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    .product-card button:hover {
      background-color: #45a049;
    }
    .product-wrapper {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }
    
  </style>
</head>
<body>
  <ul class="horizontal-menu">
    <li><a href="{{ url_for('views.home') }}">Home</a></li>
    <li><a href="{{ url_for('views.cart') }}">Cart</a></li>
    {% if current_user.is_authenticated %}
    {% if current_user.is_admin %}
    <li><a href="{{ url_for('views.admin_page') }}">Admin Page</a></li>
    <li><a href="{{ url_for('auth.edit_profile') }}">Edit Profile</a></li>
    <li><a href="{{ url_for('views.order_history') }}">Order History</a></li>
    {% else %}
    <li><a href="{{ url_for('auth.edit_profile') }}">Edit Profile</a></li>
    <li><a href="{{ url_for('views.order_history') }}">Order History</a></li>
    {% endif %}
    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
    {% else %}
    <li><a href="{{ url_for('auth.signup') }}">Register</a></li>
    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
    {% endif %}
  </ul>

  <h1>Search View</h1>
  
  <form id="search-form" action="{{ url_for('search.lookup') }}" method="GET">
    <input type="text" id="search-input" name="query" placeholder="Search..." required>
    <select id="search-criteria" name="criteria">
      <option value="title">Search by Title</option>
      <option value="author">Search by Author</option>
      <option value="genre">Search by Genre</option>
      <option value="ISBN">Search by ISBN</option>
    </select>
    <button type="submit">Search</button>
  </form>


  <div class="product-wrapper">
    <div class="product-container">
    {% for book in books %}
  <div class="product-card">
    <img src="{{ book.image_url }}" alt="" />
    <h2><a href="{{ url_for('views.product', book_id=book.id) }}">{{ book.title }}</a></h2>
    <p class="current-price">Price you pay: <span>${{ book.selling_price }}</span></p>
    <form action="{{ url_for('purchase.add_to_cart', book_id=book.id) }}" method="POST">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <button class="add-to-cart" type="submit">Add to Cart</button>
    </form>
  </div>
  {% endfor %}
</div>
</div>

</body>
</html>